@startmindmap
<style>
mindmapDiagram {
  .green0 {
    BackgroundColor #E7F6A4
  }
  .green1 {
    BackgroundColor #BACD66
  }
  .green2 {
    BackgroundColor #90A437
  }
  .red0 {
    BackgroundColor #FFBBCC
  }
  .red1 {
    BackgroundColor #BF607B
  }
  .purple0 {
    BackgroundColor #8F78AD
  }
  .purple1 {
    BackgroundColor #6B4E90
  }
}
</style>
+ Gevorderden 2 / en dos parejas
-- <$rotate_right*0.5> Setenta por las manos <<red2>>
++ <$rotate_left*0.5> Enchufla con puente <<green1>>
++ <$rotate_left*0.5> Toma electrica <<green1>>
++ <$rotate_right*0.5> Familia con regressi <<green0>>
legend right
    | Kleur | Begin figuur |
    |<#8F78AD>| Gekruist, beide handen |
    |<#6B4E90>| Gekruist, rechterhand |
'    |<#4C2D73>| ? |
'    |<#321456>| ? |
'    |<#1C053A>| ? |
    |<#E7F6A4>| Recht op recht, beide handen |
    |<#BACD66>| Recht op recht, linkerhand |
'    |<#90A437>| ? |
'    |<#687B14>| ? |
'    |<#435200>| ? |
    |<#E699AF>| Vanuit basispositie, handen loslaten |
    |<#BF607B>| Rechterhand neemt linkerhand dame rechts van u |
    |<#993350>| Hand in hand met beide dames naast u |
'    |<#BF607B>| ? |
'    |<#993350>| ? |
'    |<#73132E>| ? |
'    |<#4D0016>| ? |
endlegend
@endmindmap
